### PR TITLE
119 - Remove Redirect to Home from Edit Profile

### LINKED ISSUE #119: Add a "save and close" button for the profile edit
Currently, on the profile edit page, clicking "save" instantly redirects you back to home. This is a horrible user experience...

As a user, I want to be able to save and stay on my profile edit page. A button labeled "save and close" in addition to the "save". When I click the save button, i want to stay on the page. When i click the "save and close" button i want to close the page.

### PR DESCRIPTION
**Pull request by iameddieyayaya**
## Story

Fix #119 

## Description

Removed navigate/route hook from EditProfile Page & EditPassword Page
Added .yarnrc.yml to eslint/prettier ignore
Added APP_NAME to .env.defaults

## Solution

Remove Redirect(home) hook

## Was this feature tested on all browsers?

- [x] Chrome

## Definition of Done

- [ ] README updated
- [ ] Tests written
- [ ] Acceptance criteria implement
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

mandatory

### CODE REVIEW

**Review by house9 — APPROVED** [review]
👍

**Review by craineum — APPROVED** [review]
LGTM

**Comment by craineum** [comment]
Looks like we have some failing tests?!?

**Comment by archae0pteryx** [comment]
Can we add a second button that say's "save and close"? How does it close now?

**Pull request merged**
