### PR TITLE
Issue: #72 Upgrade redwood to 3

### PR DESCRIPTION
**Pull request by archae0pteryx**
Resolves [#72](https://github.com/CodingZeal/redwood-template-app/issues/72#issue-1374424819) 

Redwood upgrade to 3

### CODE REVIEW

**Review by craineum — COMMENTED** [review]
Looks good

❓ We didn't have to correct anything from the breaking changes list?
[Breaking Changes List](https://community.redwoodjs.com/t/redwood-3-0-0-is-now-available/3989#breaking-changes-11)

**Comment by archae0pteryx** [comment]
Not that I found. That list is also a loop back on itself so it's not very helpful. I am finding an issue with testing library but that isn't mentioned in the breaking changes list there... I started a convo about it but haven't heard anything yet. Prob wait to merge in case I have found an unknown bug. I'm debugging into it now but can't find anything obvious

**Comment by craineum** [comment]
Looks like we would need to do these:

- [Fastily v4](https://community.redwoodjs.com/t/redwood-3-0-0-is-now-available/3989#fastify-v4-and-configuring-the-fastify-instance-14)
- [Prisma v4](https://community.redwoodjs.com/t/redwood-3-0-0-is-now-available/3989#prisma-v4-16) - At least the `@unique` constraint stuff maybe [more](https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-4)?
- [Lint import order](https://community.redwoodjs.com/t/redwood-3-0-0-is-now-available/3989#fixing-the-import-order-rule-18)

I don't think we have any snapshots at this point, so [this](https://community.redwoodjs.com/t/redwood-3-0-0-is-now-available/3989#jest-v29-15) should not be an issue.

Not for this PR, but I think it would be interesting to turn on TypeScript Strict Mode and see what needs to be resolved. I may create a new issue for this.

**Comment by archae0pteryx** [comment]
@craineum apparently you had more patience than i did when looking at this post! I kept clicking on the links and they all kept taking me to the top of the same page... I will update these things! Sorry for missing that.

**Pull request merged**
